# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ╭╮╰╯
# ┌┐└┘

format = """
╭ $username@$hostname \
$all\
\
$fill \
\
$status\
$jobs\
$os\
$container\
$netns\
$shell\
$battery\
$time ╮ $line_break\
\
╰ $directory\
$character\
"""

right_format = "$cmd_duration╯"

[battery]
charging_symbol = "[ ](blue)"
unknown_symbol = "? "
disabled = true

[[battery.display]]
threshold = 15
style = 'bold red'
discharging_symbol = '󰁺 '

[[battery.display]]
threshold = 30
style = 'bold red'
discharging_symbol = '󰁻 '

[[battery.display]]
threshold = 50
style = 'bold yellow'
discharging_symbol = '󰁽 '

[[battery.display]]
threshold = 70
style = 'bold green'
discharging_symbol = '󰁿 '

[[battery.display]]
threshold = 95
style = 'bold green'
discharging_symbol = '󰂁 '

[[battery.display]]
threshold = 100
style = 'bold green'
discharging_symbol = '󰁹 '

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_length = 2
fish_style_pwd_dir_length = 1
truncation_symbol = ".../"
style = "purple bold"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[time]
disabled = false
format = "[$time]($style)"

[username]
format = "[$user]($style)"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style)"
ssh_only = false

[fill]
# symbol = "."
style = ""
